spring.application.name=ProjectWorker-Traccia16
# Key Api per eventuale integrazione di AI
spring.ai.openai.api-key=INSERISCI_LA_TUA_CHIAVE_QUI
# Riferimento del changelog-master nel caso si vorranno integrare le modifiche al DB con Liquibase
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
# Abilito la creazione automatica delle tabelle di sessione
spring.session.jdbc.initialize-schema=always
# Disabilito Docker, anche se previsto come dipendenza Maven, mi tengo pronto nel caso lo voglia
# integrare in futuro
spring.docker.compose.enabled=false

# ===============================
# CONFIGURAZIONE DATABASE POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=ProjectWorker

# Specifica il driver
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURAZIONE HIBERNATE / JPA
# ===============================
# Mostra le query SQL nel terminale
spring.jpa.show-sql=true

# Formatta le query SQL per renderle leggibili
spring.jpa.properties.hibernate.format_sql=true

# Aggiorna automaticamente lo schema del database
spring.jpa.hibernate.ddl-auto=update

# Specifica il dialetto per PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# In questo modo si indica a SpingBoot che deve prima creare le tabelle e solo dopo lanciare eventuale file di
# prepopolamento del db
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Aumentiamo il limite per il singolo file a 10MB
spring.servlet.multipart.max-file-size=10MB

# Aumentiamo il limite totale della singola richiesta (es. se carichi 3 file) a 50MB
spring.servlet.multipart.max-request-size=50MB